packaging_format = 2

id = "kbin"
name = "Kbin"
description.en = "Decentralized content aggregator and microblogging platform"
description.fr = "Agrégateur de contenu décentralisé et plateforme de microblogging"

version = "1.0~ynh1"

maintainers = ["johndoe"]

[upstream]
license = " AGPL-3.0"
website = "https://kbin.pub/"
demo = "https://kbin.social/"
admindoc = "https://codeberg.org/Kbin/kbin-core/wiki#admin-guide"
userdoc = "https://codeberg.org/Kbin/kbin-core/wiki#user-guide"
code = "https://codeberg.org/Kbin/kbin-core"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/kbin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    #[install.language]
    #ask.en = "Choose the application language"
    #ask.fr = "Choisissez la langue de l'application"
    #type = "string"
    #choices = ["fr", "en"]
    #default = "fr"

    #[install.admin]
    #type = "user"

    #[install.password]
    #help.en = "Use the help field to add an information for the admin about this question."
    #help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    #type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/Kbin/kbin-core/archive/b0e98073be7fcc60f37c7ea82a8572b4fcea7762.tar.gz"
        sha256 = "7f536faa7416e7e955f5f86fb813942cfb59d6337774a78e5c4627355a83ad2b"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    #[resources.ports]

    [resources.apt]
    packages = "git postgresql postgresql-contrib supervisor php8.2-common php8.2-fpm php8.2-cli php8.2-amqp php8.2-pgsql php8.2-gd php8.2-curl php8.2-simplexml php8.2-dom php8.2-xml php8.2-redis php8.2-intl unzip"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
