#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=7

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

mkdir $install_dir/public/media

chmod 777 $install_dir/public/media
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config using the conf/php-fpm.conf or conf/extra_php-fpm.conf
ynh_add_fpm_config --usage=low --footprint=low

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

#=================================================
# INSTALL KBIN WITH COMPOSER
#=================================================
ynh_script_progression --message="Installing $app with Composer..." --weight=5

# Install composer
ynh_exec_warn_less ynh_install_composer --install_args="--prefer-dist --no-dev --no-autoloader --no-scripts --no-progress"

pushd $install_dir
	php$phpversion bin/console cache:clear
popd

ynh_composer_exec --commands="clear-cache"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="../conf/.env.example" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# SETUP SUPERVISOR
#=================================================
ynh_script_progression --message="Configuring a supervisor service..." --weight=1

# Create a dedicated supervisor config
ynh_add_supervisor_config --service="$app" --template=messenger-worker.conf

#=================================================
# DEPLOY
#=================================================
#ynh_script_progression --message="Deploying..." --weight=1

#pushd $install_dir
#	php$phpversion bin/console doctrine:database:create
#	php$phpversion bin/console doctrine:migrations:migrate
#popd

#=================================================
# INSTALL KBIN
#=================================================
ynh_script_progression --message="Installing $app..." --weight=10

pushd $install_dir
 	ynh_use_nodejs
	ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH yarn install
	ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH NODE_ENV=production yarn build
popd

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add "supervisor" --description="Supervisor daemon for $app" --log="/var/log/$app/$app.log"

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression --message="Starting a supervisor service..." --weight=1

# Start a supervisor service
#ynh_supervisor_action --service_name="$app" --action="reload" --log_path="systemd" #--line_match="success: $app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
